### ISSUE TITLE
Using self-signed certificates

### ISSUE THREAD

**Issue by rmondegar** [idealo/mongodb-slow-operations-profiler#14]
Hello there,

  I'm trying to set up this tool in order to profile our databases but I'm unable to connect it to our mongo servers.
  Is there a way of using self signed CA/Client certificates?
  Here is my current config:

```
{
    "collector": {
        "hosts": [
            "collector-db:27017"
        ],
        "db": "mongodba",
        "collection": "slowops"
    },
    "profiled": [
        {
            "label": "OMITTED",
            "hosts": [
                "IP-OMITTED:27017"
            ],
            "ns": [
                "r-*.*"
            ],
            "slowMS": 250,
            "adminUser": "ADMIN-USER",
            "adminPw": "PASSWORD",
            "collect": true,
            "ssl": true,
	    "responseTimeoutInMs": 2000
        }
    ],
    "yAxisScale": "milliseconds",
    "adminToken": "mySecureAdminToken",
    "defaultSlowMS": 100,
    "defaultResponseTimeoutInMs": 2000,
    "defaultExcludedDBs": ["admin", "local", "config"],
    "maxWeblogEntries": 100,
    "systemProfileCollectionMaxSizeInMB": 128
}
```

This is what I see on logs:

![image](https://user-images.githubusercontent.com/60993939/135912329-73152fa1-4814-4a9b-a606-ba9f15478bef.png)

This is the output I get on the server side:

![image](https://user-images.githubusercontent.com/60993939/135912745-caa6724f-8934-4f3a-af9a-feb7de042567.png)

Best regards,

  Ralph Mondegar

**Comment by kagahd** [comment]
> Is there a way of using self signed CA/Client certificates?

Yes, of course, you can use self signed certificates. 
You just need to configure your JVM Key Store as described in MongoDB's documentation [here](https://docs.mongodb.com/drivers/java/sync/v4.3/fundamentals/connection/tls/#configure-the-jvm-key-store).

Don't forget to import your CA-Certificate to your key store beforehand, for example:
```
keytool -import -file /certs/cacert.pem -alias mongoClient -keystore /trust/mongoStore.ts -storepass StorePass
```
Your JVM system properties would then be set to:
```
javax.net.ssl.keyStore="/trust/mongoStore.ts"
javax.net.ssl.keyStorePassword="StorePass"
```

Best regards!
