### ISSUE TITLE
Disable auto increaseSizeOfSystemProfileCollection

### ISSUE THREAD

**Issue by kkrasnov1** [idealo/mongodb-slow-operations-profiler#16]
Hi,

How to disable auto increaseSizeOfSystemProfileCollection. This crashes on the on primary node (mongodb 4.4.9):

```
{"t":{"$date":"2021-12-27T07:37:04.367+03:00"},"s":"F",  "c":"CONTROL",  "id":4757800, "ctx":"thread535824","msg":"Writing fatal message","attr":{"message":"Invalid access at address: 0x98"}}
{"t":{"$date":"2021-12-27T07:37:04.368+03:00"},"s":"F",  "c":"CONTROL",  "id":4757800, "ctx":"thread535824","msg":"Writing fatal message","attr":{"message":"Got signal: 11 (Segmentation fault).\n"}}
```

**Comment by kagahd** [comment]
Hi, 
if you want to disable the increase of size of the `system.profile` collection, you can set `systemProfileCollectionMaxSizeInMB=0` in the configuration file `config.json`. 
Please refer to the [documentation of the configuration](https://github.com/idealo/mongodb-slow-operations-profiler#-configuration). 
The property `systemProfileCollectionMaxSizeInMB` has been introduced in version 3.1.0 which is documented [here](https://github.com/idealo/mongodb-slow-operations-profiler#v3.1.0). 

However, I would like to understand why it crashes your primary node. Which operating system are you using? Do you have more logs about the crash, especially from the mongodb-slow-operations-profiler tool?

**Comment by kkrasnov1** [comment]
Thank you! I'll try using "systemProfileCollectionMaxSizeInMB":0. 

More details about the problem here https://jira.mongodb.org/projects/SERVER/issues/SERVER-62276
