### ISSUE TITLE
Can set config for enableUtf8Validation?

### ISSUE THREAD

**Issue by KunkkaVN** [idealo/mongodb-slow-operations-profiler#21]
My db use query without UTF-8 format  so the tool cannot read.
![image](https://user-images.githubusercontent.com/22276728/187153066-253a2615-87db-41a8-9bf8-ce0391011669.png)

Can I add enableUtf8Validation = false in config.

**Comment by kagahd** [comment]
Is your screenshot showing the mongodb shell? How does it relate to the mongodb-slow-operation-profiler? Can you describe the issue more in detail please?

**Comment by KunkkaVN** [comment]
the mongodb-slow-operation-profiler cannot show any result at any filter. So I go to mongo shell to show profile and it get error invalid UTF-8. I use config enableUtf8Validation = false  to mongo shell to pass this error.

So, I want to ask mongodb-slow-operation-profiler has supported config enableUtf8Validation or unicode

**Comment by kagahd** [comment]
Thanks for the explanation. The mongodb-slow-operations-profiler does not know (yet) the option `enableUtf8Validation`. It would require to enhance the code to honor this option.

**Comment by kagahd** [comment]
@KunkkaVN can you please copy & paste such invalid UTF8 (query and data), so I can test if it works?

**Comment by KunkkaVN** [comment]
Yes, here is a query to my collection
`
{ op: 'query',
--
ns: 'tts.tts-cache',
command:
{ find: 'tts-cache',
filter:
{ speed: 1.2,
speaker: 4,
text: 'Dạ chị thanh toán như vậy là trễ hẹn so với hợp đồng mà chị đã cam kết với FE Credit. cho em hỏi vì sao mình thanh toán trễ vậy ạ?' },
limit: 1,
singleBatch: true,
lsid: { id: UUID("afa12fd6-fb78-49f8-a0d0-3725afc65f1b") },
'$db': 'tts-gateway',
'$readPreference': { mode: 'primaryPreferred' } },
keysExamined: 1,
docsExamined: 1,
cursorExhausted: true,
numYield: 0,
nreturned: 1,
queryHash: '6F2904CC',
planCacheKey: '0788252A',
locks:
{ ReplicationStateTransition: { acquireCount: { w: 1 } },
Global: { acquireCount: { r: 1 } },
Database: { acquireCount: { r: 1 } },
Collection: { acquireCount: { r: 1 } },
Mutex: { acquireCount: { r: 1 } } },
flowControl: {},
responseLength: 480,
protocol: 'op_msg',
millis: 0,
planSummary: 'IXSCAN { speed: -1, speaker: -1, text: 1 }',
execStats:
{ stage: 'LIMIT',
nReturned: 1,
executionTimeMillisEstimate: 0,
works: 2,
advanced: 1,
needTime: 0,
needYield: 0,
saveState: 0,
restoreState: 0,
isEOF: 1,
limitAmount: 1,
inputStage:
{ stage: 'FETCH',
nReturned: 1,
executionTimeMillisEstimate: 0,
works: 1,
advanced: 1,
needTime: 0,
needYield: 0,
saveState: 0,
restoreState: 0,
isEOF: 0,
docsExamined: 1,
alreadyHasObj: 0,
inputStage:
{ stage: 'IXSCAN',
nReturned: 1,
executionTimeMillisEstimate: 0,
works: 1,
advanced: 1,
needTime: 0,
needYield: 0,
saveState: 0,
restoreState: 0,
isEOF: 0,
keyPattern: { speed: -1, speaker: -1, text: 1 },
indexName: 'tts-query',
isMultiKey: false,
multiKeyPaths: { speed: [], speaker: [], text: [] },
isUnique: false,
isSparse: false,
isPartial: false,
indexVersion: 2,
direction: 'forward',
indexBounds:
{ speed: [ '[1.2, 1.2]' ],
speaker: [ '[4, 4]' ],
text: [ '["Dạ chị thanh toán như vậy là trễ hẹn so với hợp đồng mà chị đã cam kết với FE Credit. cho em hỏi vì sao mình thanh to...", "Dạ chị thanh toán như vậy là trễ hẹn so với hợp đồng mà chị đã cam kết với FE Credit. cho em hỏi vì sao mình thanh to..."]' ] },
keysExamined: 1,
seeks: 1,
dupsTested: 0,
dupsDropped: 0 } } },
ts: 2022-08-29T07:33:33.213Z,
client: '127.0.0.1',
allUsers: [ { user: 'admin', db: 'admin' } ],
user: 'admin@admin' }
`

**Comment by kagahd** [comment]
Can you copy & paste `db.tts-cache.stats()` please?
Can you copy & paste some relevant documents of this collection please?

**Comment by KunkkaVN** [comment]
Yes, the information of collection:

-  stats:

`
{
ns: 'tts-gateway.tts-cache',
size: 36599900,
count: 84261,
avgObjSize: 434,
storageSize: 8765440,
freeStorageSize: 897024,
capped: false,
wiredTiger: {
metadata: { formatVersion: 1 },
creationString: 'access_pattern_hint=none,allocation_size=4KB,app_metadata=(formatVersion=1),assert=(commit_timestamp=none,durable_timestamp=none,read_timestamp=none,write_timestamp=off),block_allocation=best,block_compressor=snappy,cache_resident=false,checksum=on,colgroups=,collator=,columns=,dictionary=0,encryption=(keyid=,name=),exclusive=false,extractor=,format=btree,huffman_key=,huffman_value=,ignore_in_memory_cache_size=false,immutable=false,import=(enabled=false,file_metadata=,repair=false),internal_item_max=0,internal_key_max=0,internal_key_truncate=true,internal_page_max=4KB,key_format=q,key_gap=10,leaf_item_max=0,leaf_key_max=0,leaf_page_max=32KB,leaf_value_max=64MB,log=(enabled=true),lsm=(auto_throttle=true,bloom=true,bloom_bit_count=16,bloom_config=,bloom_hash_count=8,bloom_oldest=false,chunk_count_limit=0,chunk_max=5GB,chunk_size=10MB,merge_custom=(prefix=,start_generation=0,suffix=),merge_max=15,merge_min=0),memory_page_image_max=0,memory_page_max=10m,os_cache_dirty_max=0,os_cache_max=0,prefix_compression=false,prefix_compression_min=4,readonly=false,source=,split_deepen_min_child=0,split_deepen_per_child=0,split_pct=90,tiered_object=false,tiered_storage=(auth_token=,bucket=,bucket_prefix=,local_retention=300,name=,object_target_size=10M),type=file,value_format=u,verbose=[],write_timestamp_usage=none',
type: 'file',
uri: 'statistics:table:collection-0-6744176573243531890',
LSM: {
'bloom filter false positives': 0,
'bloom filter hits': 0,
'bloom filter misses': 0,
'bloom filter pages evicted from cache': 0,
'bloom filter pages read into cache': 0,
'bloom filters in the LSM tree': 0,
'chunks in the LSM tree': 0,
'highest merge generation in the LSM tree': 0,
'queries that could have benefited from a Bloom filter that did not exist': 0,
'sleep for LSM checkpoint throttle': 0,
'sleep for LSM merge throttle': 0,
'total size of bloom filters': 0
},
'block-manager': {
'allocations requiring file extension': 21,
'blocks allocated': 6905,
'blocks freed': 5965,
'checkpoint size': 7852032,
'file allocation unit size': 4096,
'file bytes available for reuse': 897024,
'file magic number': 120897,
'file major version number': 1,
'file size in bytes': 8765440,
'minor version number': 0
},
btree: {
'btree checkpoint generation': 1447,
'btree clean tree checkpoint expiration time': Long("9223372036854775807"),
'column-store fixed-size leaf pages': 0,
'column-store internal pages': 0,
'column-store variable-size RLE encoded values': 0,
'column-store variable-size deleted values': 0,
'column-store variable-size leaf pages': 0,
'fixed-record size': 0,
'maximum internal page key size': 368,
'maximum internal page size': 4096,
'maximum leaf page key size': 2867,
'maximum leaf page size': 32768,
'maximum leaf page value size': 67108864,
'maximum tree depth': 4,
'number of key/value pairs': 0,
'overflow pages': 0,
'pages rewritten by compaction': 0,
'row-store empty values': 0,
'row-store internal pages': 0,
'row-store leaf pages': 0
},
cache: {
'bytes currently in the cache': 40974989,
'bytes dirty in the cache cumulative': 828073136,
'bytes read into cache': 37310544,
'bytes written from cache': 661765510,
'checkpoint blocked page eviction': 0,
'checkpoint of history store file blocked non-history store page eviction': 0,
'data source pages selected for eviction unable to be evicted': 0,
'eviction walk passes of a file': 0,
'eviction walk target pages histogram - 0-9': 0,
'eviction walk target pages histogram - 10-31': 0,
'eviction walk target pages histogram - 128 and higher': 0,
'eviction walk target pages histogram - 32-63': 0,
'eviction walk target pages histogram - 64-128': 0,
'eviction walk target pages reduced due to history store cache pressure': 0,
'eviction walks abandoned': 0,
'eviction walks gave up because they restarted their walk twice': 0,
'eviction walks gave up because they saw too many pages and found no candidates': 0,
'eviction walks gave up because they saw too many pages and found too few candidates': 0,
'eviction walks reached end of tree': 0,
'eviction walks restarted': 0,
'eviction walks started from root of tree': 0,
'eviction walks started from saved location in tree': 0,
'hazard pointer blocked page eviction': 0,
'history store table insert calls': 0,
'history store table insert calls that returned restart': 0,
'history store table out-of-order resolved updates that lose their durable timestamp': 0,
'history store table out-of-order updates that were fixed up by reinserting with the fixed timestamp': 0,
'history store table reads': 0,
'history store table reads missed': 0,
'history store table reads requiring squashed modifies': 0,
'history store table truncation by rollback to stable to remove an unstable update': 0,
'history store table truncation by rollback to stable to remove an update': 0,
'history store table truncation to remove an update': 0,
'history store table truncation to remove range of updates due to key being removed from the data page during reconciliation': 0,
'history store table truncation to remove range of updates due to out-of-order timestamp update on data page': 0,
'history store table writes requiring squashed modifies': 0,
'in-memory page passed criteria to be split': 0,
'in-memory page splits': 0,
'internal pages evicted': 0,
'internal pages split during eviction': 0,
'leaf pages split during eviction': 1,
'modified pages evicted': 1,
'overflow pages read into cache': 0,
'page split during eviction deepened the tree': 0,
'page written requiring history store records': 0,
'pages read into cache': 320,
'pages read into cache after truncate': 0,
'pages read into cache after truncate in prepare state': 0,
'pages requested from the cache': 352288,
'pages seen by eviction walk': 0,
'pages written from cache': 6297,
'pages written requiring in-memory restoration': 0,
'tracked dirty bytes in the cache': 141058,
'unmodified pages evicted': 0
},
cache_walk: {
'Average difference between current eviction generation when the page was last considered': 0,
'Average on-disk page image size seen': 0,
'Average time in cache for pages that have been visited by the eviction server': 0,
'Average time in cache for pages that have not been visited by the eviction server': 0,
'Clean pages currently in cache': 0,
'Current eviction generation': 0,
'Dirty pages currently in cache': 0,
'Entries in the root page': 0,
'Internal pages currently in cache': 0,
'Leaf pages currently in cache': 0,
'Maximum difference between current eviction generation when the page was last considered': 0,
'Maximum page size seen': 0,
'Minimum on-disk page image size seen': 0,
'Number of pages never visited by eviction server': 0,
'On-disk page image sizes smaller than a single allocation unit': 0,
'Pages created in memory and never written': 0,
'Pages currently queued for eviction': 0,
'Pages that could not be queued for eviction': 0,
'Refs skipped during cache traversal': 0,
'Size of the root page': 0,
'Total number of pages currently in cache': 0
},
'checkpoint-cleanup': {
'pages added for eviction': 0,
'pages removed': 0,
'pages skipped during tree walk': 0,
'pages visited': 88188
},
compression: {
'compressed page maximum internal page size prior to compression': 4096,
'compressed page maximum leaf page size prior to compression ': 131072,
'compressed pages read': 317,
'compressed pages written': 5689,
'page written failed to compress': 0,
'page written was too small to compress': 608
},
cursor: {
'Total number of entries skipped by cursor next calls': 0,
'Total number of entries skipped by cursor prev calls': 0,
'Total number of entries skipped to position the history store cursor': 0,
'Total number of pages skipped without reading by cursor next calls': 0,
'Total number of pages skipped without reading by cursor prev calls': 0,
'Total number of times a search near has exited due to prefix config': 0,
'bulk loaded cursor insert calls': 0,
'cache cursors reuse count': 91134,
'close calls that result in cache': 91136,
'create calls': 30,
'cursor next calls that skip due to a globally visible history store tombstone': 0,
'cursor next calls that skip greater than or equal to 100 entries': 0,
'cursor next calls that skip less than 100 entries': 423,
'cursor prev calls that skip due to a globally visible history store tombstone': 0,
'cursor prev calls that skip greater than or equal to 100 entries': 0,
'cursor prev calls that skip less than 100 entries': 1,
'insert calls': 7182,
'insert key and value bytes': 3297559,
modify: 0,
'modify key and value bytes affected': 0,
'modify value bytes modified': 0,
'next calls': 39832,
'open cursor count': 0,
'operation restarted': 0,
'prev calls': 1,
'remove calls': 0,
'remove key bytes removed': 0,
'reserve calls': 0,
'reset calls': 182603,
'search calls': 338011,
'search history store calls': 0,
'search near calls': 0,
'truncate calls': 0,
'update calls': 0,
'update key and value bytes': 0,
'update value size change': 0
},
reconciliation: {
'approximate byte size of timestamps in pages written': 0,
'approximate byte size of transaction IDs in pages written': 0,
'dictionary matches': 0,
'fast-path pages deleted': 0,
'internal page key bytes discarded using suffix compression': 10978,
'internal page multi-block writes': 0,
'internal-page overflow keys': 0,
'leaf page key bytes discarded using prefix compression': 0,
'leaf page multi-block writes': 298,
'leaf-page overflow keys': 0,
'maximum blocks required for a page': 1,
'overflow values written': 0,
'page checksum matches': 0,
'page reconciliation calls': 911,
'page reconciliation calls for eviction': 0,
'pages deleted': 0,
'pages written including an aggregated newest start durable timestamp ': 0,
'pages written including an aggregated newest stop durable timestamp ': 0,
'pages written including an aggregated newest stop timestamp ': 0,
'pages written including an aggregated newest stop transaction ID': 0,
'pages written including an aggregated newest transaction ID ': 0,
'pages written including an aggregated oldest start timestamp ': 0,
'pages written including an aggregated prepare': 0,
'pages written including at least one prepare': 0,
'pages written including at least one start durable timestamp': 0,
'pages written including at least one start timestamp': 0,
'pages written including at least one start transaction ID': 0,
'pages written including at least one stop durable timestamp': 0,
'pages written including at least one stop timestamp': 0,
'pages written including at least one stop transaction ID': 0,
'records written including a prepare': 0,
'records written including a start durable timestamp': 0,
'records written including a start timestamp': 0,
'records written including a start transaction ID': 0,
'records written including a stop durable timestamp': 0,
'records written including a stop timestamp': 0,
'records written including a stop transaction ID': 0
},
session: {
'object compaction': 0,
'tiered operations dequeued and processed': 0,
'tiered operations scheduled': 0,
'tiered storage local retention time (secs)': 0,
'tiered storage object size': 0
},
transaction: {
'race to read prepared update retry': 0,
'rollback to stable history store records with stop timestamps older than newer records': 0,
'rollback to stable inconsistent checkpoint': 0,
'rollback to stable keys removed': 0,
'rollback to stable keys restored': 0,
'rollback to stable restored tombstones from history store': 0,
'rollback to stable restored updates from history store': 0,
'rollback to stable sweeping history store keys': 0,
'rollback to stable updates removed from history store': 0,
'transaction checkpoints due to obsolete pages': 0,
'update conflicts': 0
}
},
nindexes: 2,
indexBuilds: [],
totalIndexSize: 12918784,
totalSize: 21684224,
indexSizes: { _id_: 2052096, 'tts-query': 10866688 },
scaleFactor: 1,
ok: 1
}
`
- Some documents of collection:

 ```
[{
 "_id": {
    "$oid": "62d66d00d55576f92b9123d7"
  },
  "text": "Dạ vâng. Em chào chị anh. chị vui lòng lưu ý không cung cấp mã OTP hoặc các thông tin cá nhân cho người thứ 3 kể cả nhân viên công ty để tránh bị giả danh lừa đảo?",
  "speed": 1.2,
  "speaker": 4,
  "hitBox": 1,
  "ltc": true,
  "createAt": {
    "$date": {
      "$numberLong": "1658244976015"
    }
  },
  "lastAccessAt": {
    "$date": {
      "$numberLong": "1658244976015"
    }
  }
},{
  "_id": {
    "$oid": "62d697b4d55576f92b9123d8"
  },
  "speed": 1.2,
  "speaker": 4,
  "text": "Cho em hỏi có phải chị lan đang nghe máy đúng không ạ?",
  "hitBox": 1,
  "ltc": true,
  "createAt": {
    "$date": {
      "$numberLong": "1658255908017"
    }
  },
  "lastAccessAt": {
    "$date": {
      "$numberLong": "1658255908017"
    }
  }
},{
  "_id": {
    "$oid": "62d697b4d55576f92b9123d9"
  },
  "speed": 1.2,
  "speaker": 4,
  "text": "Ngoài ra, khi hoàn tất hợp đồng thì bên em có gửi mã OTP gồm 4 chữ số vào điện thoại của chị để kí điện tử, cho em hỏi chị nhập dãy số này trên điện thoại của mình đúng không ạ?",
  "hitBox": 1,
  "ltc": true,
  "createAt": {
    "$date": {
      "$numberLong": "1658255908096"
    }
  },
  "lastAccessAt": {
    "$date": {
      "$numberLong": "1658255908096"
    }
  }
},{
  "_id": {
    "$oid": "62d697b4d55576f92b9123da"
  },
  "speed": 1.2,
  "speaker": 4,
  "text": "Dạ vâng, em sẽ gọi lại cho chị sau ạ. Em cảm ơn và chúc chị một ngày tốt lành.",
  "hitBox": 1,
  "ltc": true,
  "createAt": {
    "$date": {
      "$numberLong": "1658255908263"
    }
  },
  "lastAccessAt": {
    "$date": {
      "$numberLong": "1658255908263"
    }
  }
},{
  "_id": {
    "$oid": "62d697b4d55576f92b9123db"
  },
  "speed": 1.2,
  "speaker": 4,
  "text": "Em cảm ơn ạ, quá trình giải ngân và làm Hợp đồng cho Khách Hàng là hoàn toàn miễn phí, chị lưu ý không thanh toán thêm tiền bồi dưỡng, tiền hoa hồng hoặc bất kì khoản phí nào cho nhân viên nhé . Khi cần hỗ trợ, chị vui lòng liên hệ tổng đài 1 9 0 0 6 5 3 5. Em cảm ơn và chúc chị một ngày tốt lành.",
  "hitBox": 1,
  "ltc": true,
  "createAt": {
    "$date": {
      "$numberLong": "1658255908579"
    }
  },
  "lastAccessAt": {
    "$date": {
      "$numberLong": "1658255908579"
    }
  }
}]
```

**Comment by KunkkaVN** [comment]
sorry to paste long informations. I don't know how to limit block quotes

**Comment by kagahd** [comment]
Thanks. I hope I'll have time this week to review it. I'll come back to you asap.

**Comment by kagahd** [comment]
Hi @KunkkaVN 
I tried to reproduce your issue but I did not encounter any errors or issues.
Here is what I did step-by-step:

I used docker to spin up the slow-operations-profiler as described [here](https://github.com/idealo/mongodb-slow-operations-profiler#starting-up-by-using-docker) .
Enter into test-db: `docker exec -it test-db /bin/bash`
Open mongo shell: `mongo`
Use test db: `use test`
Insert some documents: 
```
db.test.insertMany([{
 "text": "Dạ vâng. Em chào chị anh. chị vui lòng lưu ý không cung cấp mã OTP hoặc các thông tin cá nhân cho người thứ 3 kể cả nhân viên công ty để tránh bị giả danh lừa đảo?",
 "speed": 1.2,
 "speaker": 4,
 "hitBox": 1,
 "ltc": true
},{
 "speed": 1.2,
 "speaker": 4,
 "text": "Cho em hỏi có phải chị lan đang nghe máy đúng không ạ?",
 "hitBox": 1,
 "ltc": true,
},{
 "speed": 1.2,
 "speaker": 4,
 "text": "Ngoài ra, khi hoàn tất hợp đồng thì bên em có gửi mã OTP gồm 4 chữ số vào điện thoại của chị để kí điện tử, cho em hỏi chị nhập dãy số này trên điện thoại của mình đúng không ạ?",
 "hitBox": 1,
 "ltc": true,
},{
 "speed": 1.2,
 "speaker": 4,
 "text": "Dạ vâng, em sẽ gọi lại cho chị sau ạ. Em cảm ơn và chúc chị một ngày tốt lành.",
 "hitBox": 1,
 "ltc": true,
},{
 "speed": 1.2,
 "speaker": 4,
 "text": "Em cảm ơn ạ, quá trình giải ngân và làm Hợp đồng cho Khách Hàng là hoàn toàn miễn phí, chị lưu ý không thanh toán thêm tiền bồi dưỡng, tiền hoa hồng hoặc bất kì khoản phí nào cho nhân viên nhé . Khi cần hỗ trợ, chị vui lòng liên hệ tổng đài 1 9 0 0 6 5 3 5. Em cảm ơn và chúc chị một ngày tốt lành.",
 "hitBox": 1,
 "ltc": true,
}])
```
Open slow-operations-profiler in browser at its [default URL](http://localhost:8080/mongodb-slow-operations-profiler/app?adminToken=mySecureAdminToken).
Activate profiling with a threshold of 0 ms on the test db in the GUI.
Execute some find queries on test db: `db.test.find({ speed: 1.2, speaker: 4, text: 'Cho em hỏi có phải chị lan đang nghe máy đúng không ạ?'}).limit(1)`
Activate collecting in the GUI.
Execute some more find queries on test db: `db.test.find({ speed: 1.2, speaker: 4, text: 'Cho em hỏi có phải chị lan đang nghe máy đúng không ạ?'}).limit(1)`
Then the profiler showed that 7 queries were already collected on test db:
<img width="1485" alt="app" src="https://user-images.githubusercontent.com/17042479/187530938-abdefe89-2a87-4b74-a263-833b196044cc.png">

Select test db in the GUI and click on `analyze`.
In the table some `insert`and `find` queries were shown:
<img width="500" alt="table" src="https://user-images.githubusercontent.com/17042479/187531946-609dd489-729e-4e37-82e0-69077ad03f0c.png">

Click the `example` link within the `find` queries.
An example of such a slow operation was shown:
<img width="1148" alt="example" src="https://user-images.githubusercontent.com/17042479/187528564-19bb5d6f-a4c4-4d4a-a068-28b45cf4e9b2.png">

Also, when I use the mongo shell as you did to show the slow operations, it works without problems:

```
test> db.system.profile.find().sort({$natural:-1}).limit(3)
[
  {
    op: 'query',
    ns: 'test.test',
    command: {
      find: 'test',
      filter: {
        speed: 1.2,
        speaker: 4,
        text: 'Cho em hỏi có phải chị lan đang nghe máy đúng không ạ?'
      },
      limit: 1,
      lsid: { id: UUID("6a9f8c6a-b6a1-4411-ac4b-fa14ed0f0f4e") },
      '$db': 'test'
    },
    keysExamined: 0,
    docsExamined: 2,
    cursorExhausted: true,
    numYield: 0,
    nreturned: 1,
    queryHash: '6F2904CC',
    planCacheKey: 'E95E179D',
    locks: {
      ReplicationStateTransition: { acquireCount: { w: Long("1") } },
      Global: { acquireCount: { r: Long("2") } },
      Mutex: { acquireCount: { r: Long("1") } }
    },
    flowControl: {},
    storage: {},
    responseLength: 256,
    protocol: 'op_msg',
    millis: 0,
    planSummary: 'COLLSCAN',
    execStats: {
      stage: 'LIMIT',
      nReturned: 1,
      executionTimeMillisEstimate: 0,
      works: 4,
      advanced: 1,
      needTime: 2,
      needYield: 0,
      saveState: 0,
      restoreState: 0,
      isEOF: 1,
      limitAmount: 1,
      inputStage: {
        stage: 'COLLSCAN',
        filter: {
          '$and': [
            { speaker: [Object] },
            { speed: [Object] },
            { text: [Object] }
          ]
        },
        nReturned: 1,
        executionTimeMillisEstimate: 0,
        works: 3,
        advanced: 1,
        needTime: 2,
        needYield: 0,
        saveState: 0,
        restoreState: 0,
        isEOF: 0,
        direction: 'forward',
        docsExamined: 2
      }
    },
    ts: ISODate("2022-08-30T20:07:56.749Z"),
    client: '127.0.0.1',
    appName: 'mongosh 1.1.9',
    allUsers: [],
    user: ''
  }
```

So I don't see at which point you get the error you have shown.
Maybe you need to describe it more in detail step-by-step as I did.

**Comment by KunkkaVN** [comment]
Thank you for supporting. I had found the problem. I had removed config `"collect": true` so It hadn't any action when click analyst. I apologize for my mistake. Thank you so much!

**Comment by kagahd** [comment]
Hi @KunkkaVN, great to hear that it works for you! I'm happy that I could help.
