### ISSUE TITLE
TLS connection settings question

### ISSUE THREAD

**Issue by pryhodkin** [idealo/mongodb-slow-operations-profiler#25]
Hi Idealo team,

Could you, please, discribe how to configure the application to connect to mongodb with tls certificates? There is an option ```ssl=true``` but there if no option to put client certificate with key and the certificate authority to validate the server certificate.

And another question about the compatibility with mongodb 6.0, does the application support it?

Thank you in advance,
Yaroslav

**Comment by kagahd** [comment]
Hi @pryhodkin, you may use both VM options `javax.net.ssl.trustStore` and `javax.net.ssl.trustStorePassword` for your client. For example: `-Djavax.net.ssl.trustStore="/tmp/ssl/MyJavaKeyStore2.store" -Djavax.net.ssl.trustStorePassword="123456"` 

> mongodb 6.0, does the application support it?

Do you mean that the instances to be profiled are mongodb 6.0 or do you mean that the app, launched by docker-compose, is to be mongodb 6.0? For the first, just try if it works and report back 😄 

Hope this helps!

**Comment by kagahd** [comment]
> Do you mean that the instances to be profiled are mongodb 6.0 or do you mean that the app, launched by docker-compose, is to be mongodb 6.0? 

I tried out both in [issue 27](https://github.com/idealo/mongodb-slow-operations-profiler/issues/27#issuecomment-1620304560). Both worked out without problems, so it seems that the mongodb-slow-operations-profiler is compatible to mongodb 6.0
