### ISSUE TITLE
Is the profiler compatible with MongoDB v6.0.3 and MongoSH 1.9.1

### ISSUE THREAD

**Issue by GouthamVJain** [idealo/mongodb-slow-operations-profiler#27]
Enabling Profiling and Node Status is not been updated in the GUI. 
We are not able to enable profile and get the Query delays

**Comment by kagahd** [comment]
Do you use browser plug-ins which may block?

**Comment by GouthamVJain** [comment]
I have used it for Mongo 4.2 and we did not see an issue. But with Mongo 6.x we see that the profiling commands are not working from GUI.

**Comment by kagahd** [comment]
Thanks for the info! So it seems that Mongo v6 is incompatible. We will have a look at it.

**Comment by kagahd** [comment]
I tested successfully with mongodb v6.0.7 and mongsh v1.10.1 by using [docker-compose](https://github.com/idealo/mongodb-slow-operations-profiler/blob/master/docker-compose.yaml). 
I first used the image `mongo:6.0` for the `test-db` which worked without problems. Then I used also the image `mongo:6.0` for the `collector-db` which also worked without problems. 
In both cases I could set the `slow ms threshold`, start `profiling` and start `collecting`. The changes were instantly reflected in the GUI. 
I set the `slow ms threshold` to 0 ms to collect everything. Then I inserted some documents into the `test-db`. After having clicked the link `refresh`, the GUI showed that slow operations (all my inserts) were collected. 
Also clicking on `analyze` opened the analysis page and showed the collected slow operations.

Could you please describe more in detail what OS, mongo version, flavor (jammy, focal, nanoserver etc.) and environment you are using so I have a chance to reproduce the issue?

Could you also do the same test as I did with [docker-compose](https://github.com/idealo/mongodb-slow-operations-profiler/blob/master/docker-compose.yaml) I described above and report back?
Thanks!

**Comment by kagahd** [comment]
Closed, as there was no reply from the requester how to reproduce.
