### ISSUE TITLE
Is there a way to run 2+ collectors but single web interface

### ISSUE THREAD

**Issue by rickalm-wapo** [idealo/mongodb-slow-operations-profiler#5]
Given the size of our environment I'd like to have a profiler running per cluster storing data in the same collector and then another copy only serving web requests.

Thoughts ?

**Comment by kagahd** [comment]
Yes, of course, this is possible and even the way how this generally works. Have a look at the [example configuration](https://github.com/idealo/mongodb-slow-operations-profiler#-configuration). You can see there in the array "profiled", that two collectors are defined:
One is labeled "dbs foo" and the other "dbs bar". Both are collecting slow operations from different database systems into the same collector database. The collector database is defined at the beginning of the configuration in the section "collector". 
The [application status page](https://github.com/idealo/mongodb-slow-operations-profiler#applicaton-status-page) of the web interface will show both database systems. 
The [analysis page](https://github.com/idealo/mongodb-slow-operations-profiler#example-screenshot-of-the-analysis-page) will analyze slow operations stored in the globally used collector database.
Hope this helps!

**Comment by rickalm-wapo** [comment]
I guess I didn't describe the issue correctly.

When I include all of our MongoD instances (ns: *.*) there are over 2000 "Threads" trying to monitor and insert into the database.

What I wanted to do was have a series of "collector" instances of the tomcat application reading data and inserting into the collection database and then have a seperate set of tomcat instances actually serving up the web pages.

I realize I can have a different tomcat instance per replica set, but we were hoping to be able to have a single web interface for all clusters in our environment vs running 30+ web sites that users need to navigate through

**Comment by kagahd** [comment]
Okay, now I understand better what you want to do. 
You could actually deploy multiple instances of the slow-ops profiling tool on multiple instances of Tomcat. Each instance would have the same Collector database defined but different databases (aka namespaces) to profile.
To have a consistent web GUI, I suggest another Tomcat instance that defines all databases to be profiled, but does not actively profile/collect them. 

This way, all other Tomcat instances write to the globally used Collector database and thus distribute the load of the many collector threads over many Tomcat instances, while there is a single Tomcat instance for a single web GUI. This Tomcat instance knows all your profiled databases, so it can show them all together in one web GUI. It also knows about the globally used Collector database, so it can query it to analyze the collected slow operations for all your namespaces. 
However, if you want to start/stop collecting, you have to use the related Tomcat web app which is collecting from the concerned database.

**Comment by rickalm-wapo** [comment]
That was what I did, but then the "app" web page had no data on slow queries in the right side columns I was concerned that there were other potential issues I might not be aware of so I backed off from that approach

The reason I opened this ticket was mostly to get some perspective on the code. I'm assuming the profileD state is split between the collector DB and in-memory status in the tomcat app which is why some of the information is empty.

When you said profile/collect them that also brought up an interesting question. There are 2 columns in the "app" page. Am I correct in assuming that the "profile" true/false is representing the state of the mongoD configuration and "collecting" true/false is the state of the slow-query tomcat app.

Thanks again for the help

collector prod
`{
  "collector": {
    "hosts": [
      "collector-db:27017"
    ],
    "db": "mongodba",
    "collection": "slowops"
  },
  "profiled": [
    {
      "enabled": true,
      "label": "prod-mongod1",
      "adminUser": "user",
      "adminPw": "pass",
      "hosts": [
        "prod-mongod1.domain:27018",
      ],
      "ns": [
        "*.*"
      ]
    }
  ],
  "yAxisScale": "seconds",
  "adminToken": "token",
  "defaultSlowMS": 250,
  "defaultResponseTimeoutInMs": 10000,
  "maxWeblogEntries": 300
}`

collector dev
`{
  "collector": {
    "hosts": [
      "collector-db:27017"
    ],
    "db": "mongodba",
    "collection": "slowops"
  },
  "profiled": [
    {
      "enabled": true,
      "label": "dev-mongod1",
      "adminUser": "user",
      "adminPw": "pass",
      "hosts": [
        "dev-mongod1.domain:27018",
      ],
      "ns": [
        "*.*"
      ]
    }
  ],
  "yAxisScale": "seconds",
  "adminToken": "token",
  "defaultSlowMS": 250,
  "defaultResponseTimeoutInMs": 10000,
  "maxWeblogEntries": 300
}`

WEB
`{
  "collector": {
    "hosts": [
      "collector-db:27017"
    ],
    "db": "mongodba",
    "collection": "slowops"
  },
  "profiled": [
    {
      "enabled": false,
      "label": "prod-mongod1",
      "adminUser": "user",
      "adminPw": "pass",
      "hosts": [
        "prod-mongod1.domain:27018",
      ],
      "ns": [
        "*.*"
      ]
    },
    {
      "enabled": false,
      "label": "dev-mongod1",
      "adminUser": "user",
      "adminPw": "pass",
      "hosts": [
        "dev-mongod1.domain:27018",
      ],
      "ns": [
        "*.*"
      ]
    }
  ],
  "yAxisScale": "seconds",
  "adminToken": "token",
  "defaultSlowMS": 250,
  "defaultResponseTimeoutInMs": 10000,
  "maxWeblogEntries": 300
}`

**Comment by kagahd** [comment]
Yes, you got it right.

> but then the "app" web page had no data on slow queries in the right side columns I was concerned that there were other potential issues

Do you mean the columns that show the last collected operations for the last X seconds or minutes? You are right, these columns will remain empty in the "app" web page because the state of these columns is only known to the web app which is actively collecting the slow operations.
However, even if these columns are empty, you can tick the checkboxes to select the databases you are interested in to analyze and then click the `analyze` link. This should show you all collected slow operations of the selected databases/namespaces.

You are also correct that the "profile" true/false is representing the state of the mongoD configuration and "collecting" true/false is the state of the slow-query tomcat app. So "profiling" is set on the database while "collecting" is set on the web app. 
"Profiling:true" means that slow operations get copied to the capped collection `system.profile` of the profiled database. This is done by mongoD itself. You can switch it on/off in any instance of any of your slow-ops web apps.
"Collecting:true" means that documents are copied from the capped collection `system.profile` of the profiled database into the globally used collector database. This is done by the slow-ops tool running on Tomcat. You can switch it on/off only on the instance of the slow-ops web app which belongs to the database being profiled/collected.
